-- MySQL Script generated by MySQL Workbench
-- Tue Oct 14 17:04:29 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema rozetka_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `rozetka_db` ;

-- -----------------------------------------------------
-- Schema rozetka_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rozetka_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `rozetka_db` ;

-- -----------------------------------------------------
-- Table `rozetka_db`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rozetka_db`.`city` (
  `city_id` INT NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`city_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rozetka_db`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rozetka_db`.`company` (
  `company_id` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`company_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rozetka_db`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rozetka_db`.`customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(255) NOT NULL,
  `customer_surname` VARCHAR(255) NOT NULL,
  `customer_email` VARCHAR(255) NULL DEFAULT NULL,
  `customer_phone` VARCHAR(20) NULL,
  PRIMARY KEY (`customer_id`),
  INDEX `idx_customer_email` (`customer_surname` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rozetka_db`.`customer_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rozetka_db`.`customer_card` (
  `card_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `card_number` VARCHAR(255) NOT NULL,
  `bonus_num` INT NULL DEFAULT NULL,
  PRIMARY KEY (`card_id`),
  INDEX `customer_id` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `customer_card_ibfk_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `rozetka_db`.`customer` (`customer_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rozetka_db`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rozetka_db`.`order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `order_date` DATE NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `customer_id` (`customer_id` ASC) VISIBLE,
  INDEX `idx_order_date` (`order_date` ASC) VISIBLE,
  CONSTRAINT `order_ibfk_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `rozetka_db`.`customer` (`customer_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rozetka_db`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rozetka_db`.`delivery` (
  `delivery_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `city_id` INT NOT NULL,
  `delivery_method` VARCHAR(255) NOT NULL,
  `delivery_address` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`delivery_id`),
  INDEX `order_id` (`order_id` ASC) VISIBLE,
  INDEX `city_id` (`city_id` ASC) VISIBLE,
  CONSTRAINT `delivery_ibfk_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `rozetka_db`.`order` (`order_id`),
  CONSTRAINT `delivery_ibfk_2`
    FOREIGN KEY (`city_id`)
    REFERENCES `rozetka_db`.`city` (`city_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rozetka_db`.`product_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rozetka_db`.`product_type` (
  `product_type_id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(255) NOT NULL,
  `type_description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`product_type_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rozetka_db`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rozetka_db`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `product_type_id` INT NOT NULL,
  `product_name` VARCHAR(255) NOT NULL,
  `product_description` TEXT NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `company_id` (`company_id` ASC) VISIBLE,
  INDEX `product_type_id` (`product_type_id` ASC) VISIBLE,
  INDEX `idx_product_name` (`product_name` ASC) VISIBLE,
  CONSTRAINT `product_ibfk_1`
    FOREIGN KEY (`company_id`)
    REFERENCES `rozetka_db`.`company` (`company_id`),
  CONSTRAINT `product_ibfk_2`
    FOREIGN KEY (`product_type_id`)
    REFERENCES `rozetka_db`.`product_type` (`product_type_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rozetka_db`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rozetka_db`.`order_item` (
  `order_item_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`order_item_id`),
  INDEX `order_id` (`order_id` ASC) VISIBLE,
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `order_item_ibfk_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `rozetka_db`.`order` (`order_id`),
  CONSTRAINT `order_item_ibfk_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `rozetka_db`.`product` (`product_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rozetka_db`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rozetka_db`.`payment` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `payment_method` VARCHAR(255) NOT NULL,
  `payment_status` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `order_id` (`order_id` ASC) VISIBLE,
  CONSTRAINT `payment_ibfk_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `rozetka_db`.`order` (`order_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rozetka_db`.`product_attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rozetka_db`.`product_attribute` (
  `attribute_id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `attribute_name` VARCHAR(255) NOT NULL,
  `attribute_value` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`attribute_id`),
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `product_attribute_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `rozetka_db`.`product` (`product_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rozetka_db`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rozetka_db`.`reviews` (
  `review_id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `review_text` TEXT NULL DEFAULT NULL,
  `rating` INT NULL DEFAULT NULL,
  PRIMARY KEY (`review_id`),
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  INDEX `customer_id` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `reviews_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `rozetka_db`.`product` (`product_id`),
  CONSTRAINT `reviews_ibfk_2`
    FOREIGN KEY (`customer_id`)
    REFERENCES `rozetka_db`.`customer` (`customer_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rozetka_db`.`wishlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rozetka_db`.`wishlist` (
  `wishlist_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`wishlist_id`),
  INDEX `customer_id` (`customer_id` ASC) VISIBLE,
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `wishlist_ibfk_1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `rozetka_db`.`customer` (`customer_id`),
  CONSTRAINT `wishlist_ibfk_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `rozetka_db`.`product` (`product_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
