# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy

name: Build and deploy Python app to Azure Web App - mydatabaseapp

on:
  push:
    branches:
      - lab4-branch # Цей робочий процес запускається при пуші в гілку lab4-branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонуємо репозиторій
      - uses: actions/checkout@v4

      # 2. Налаштовуємо Python
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 3. Створюємо віртуальне середовище та встановлюємо залежності
      - name: Create virtual environment and install dependencies
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt
      # 4. Завантажуємо артефакт для деплою (виключаючи віртуальне середовище)
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !antenv/
  deploy:
    runs-on: ubuntu-latest
    needs: build 
    steps:
      # 1. Завантажуємо артефакти з build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # 2. Деплой на Azure через Publish Profile
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'mydatabaseapp'
          slot-name: 'Production'
          # !!! ВИКОРИСТАННЯ СЕКРЕТА !!!
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} 
          package: .
